# Welcome to Jekyll!
#
# Site settings
title: Charles Hudson
email: work@charleshudson.com
github_username: phobetron
description: >-
  Full-Stack Software Engineer with experience in User Experience and Service Oriented Architecture
baseurl: ""
url: "https://charleshudson.com"

# Server settings
host: "0.0.0.0"
port: 8080

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
plugins:
  - github-pages
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - app/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
